services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      retries: 5
      start_period: 20s

networks:
  default:
    name: local
    external: true
